my first home work
VladyslavAbramov/ilfe-hw1 pull request #1
Opened 2017-02-14 11:10 UTC by VladyslavAbramov

2017-02-17 11:59 UTC, BertaFly commented on style2.css
> +.avatar {
картинкам надо давать ширину 100%, потому что ширину лучше задать блоку, в котором она находится. эта привычка облегчит жизнь, когда будешь делать адаптивный дизайн. при изменении ширины экрана, на котором просматривают твою страницу, картинка будет масштабироваться, а не иметь постоянную ширину в 140 пикселей.

2017-02-17 12:00 UTC, BertaFly reviewed
все отлично, придралась тока к картинке, но все о хорошо, можно мерджить.

2017-02-17 12:21 UTC, BertaFly approved these changes

2017-02-22 18:52 UTC, egemon requested changes

2017-02-22 18:52 UTC, egemon commented on index2.html
> +        <!-- хорошее решение с текстом и оберткой-->
Удаляй мои комменты, они уже ни к чему)

2017-02-22 18:52 UTC, egemon commented on style2.css
> +}
эти значки в конце показывают, что лучше в конце каждого файла, который добавляешь в гит добавлять пустую строку. Так как перенос строки состоит из двух симоволов: конца прошлой - он находится на прошлой строке и начала новой, то любое добавление строки в конец файла будет считаться также изменением последней строки. И последняя строка будет показывать и с + и с -. То есть как будто ты ее удалил и заново добавил, а на самом деле ты просто добавил конец строки в нее.

2017-02-22 19:25 UTC, VladyslavAbramov commented on style2.css
> +}
Понял, уже исправил.

2017-02-25 15:37 UTC, merged