lesson4
VladyslavAbramov/ilfe-hw1 pull request #3
Opened 2017-03-14 16:29 UTC by VladyslavAbramov

2017-03-17 09:33 UTC, donurg commented on lesson4/index.html
> +			<img class="page1 absolute" src="img/page3.png">
Тут, вероятно, возникнет комментарий по BEM — модификатор absolute не должен быть отдельно от блока или элемента.

2017-03-17 09:33 UTC, donurg commented on lesson4/index.html
> +			<img class="page4 absolute" src="img/page1miror.png">
http://www.hongkiat.com/blog/css-reflection/ — зеркальный эффект можно задать с помощью CSS

2017-03-17 09:33 UTC, donurg commented on lesson4/index.html
> +			<img class="shadow__picture" src="img/shadow.png">
http://red-team-design.com/how-to-create-slick-effects-with-css3-box-shadow/ — опять же, тут можно с CSS

2017-03-17 09:33 UTC, donurg commented on lesson4/index.html
> +				<img class="article__picture-big" src="img/article6.png">
big — тут лучше подойдет нейминг как для модификатора (если по BEM)

2017-03-17 09:33 UTC, donurg commented on lesson4/index.html
> +					</button>
тут, вероятно, не button, а input type="submit"

2017-03-17 09:33 UTC, donurg commented on lesson4/style.css
> +	z-index: 1; /*  не работает*/
я попробовал порисерчить, но не нашел
но, опять же, можно попробовать сделать тень через box-shadow и тогда не понадобится z-index

2017-03-17 12:12 UTC, egemon requested changes

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +		<div class="header__centre">
why do you need these wrappers eveywhere? you can create class that adds padding. and use this class for each section

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +			<img class="page1" src="img/page3.png">
maybe preview_page or preview_img

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +			<form class="subscription__mail">
subscription__form

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +		<article class="article">
it is not an article, it seems like container for 6 articles don't you think?

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +			<div class="article__item">
and each this item seems to be independent. So it could be article, with article__img, article__text and article__button

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +				<img class="article__picture--big" src="img/article4.png">
article__picture article__picture--big - you should use both in BEM. in first - general styles, in second modifier styles

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +	<div class="pre-footer">
it seems like footer actually.

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +					<textarea class="pre-footer__textarea placeholder" placeholder="Your message"></textarea>
placeholder in the center of field. I don't like it.

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +		<div class="footer__centre">
remove all those extra wrappers. Here all you need is text-alling: left. And this is the default value

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	list-style: none;
I guess list-style: none is ok for all ul's on this page.

2017-03-17 12:12 UTC, egemon commented on lesson4/index.html
> +				<img class="header__picture" src="img/logo.png">
img should be also a link

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	text-decoration: none;
the same here. Probably it is ok for all a on page

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	background-image: url(img/grad.png);
try to make this gradient with css3

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	display: flex;
why do you need flex here? all blocks inside seems vertically one by one like in usual box model

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	flex-direction: column;
no need at all. DOn't use it just because you can. Devs will spend a lot of time to understand why you used it

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	text-transform: capitalize;
:+1:

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	width: 190px;
no fixed width. Remember about translations

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	-webkit-box-reflect: below 2px -webkit-gradient(linear, left top, left bottom, from(transparent), color-stop(70%, transparent) , to(rgba(250, 250, 250, 0.1)));
good, but it is won't work across. So just make image to include this reflection too.

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	z-index: 2; /* не знаю почему, но не работает */
it works, but i don't know what are you trying to achieve

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	align-items: center;
why?

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +.subscription:before, .subscription:after {
1) you could use images. These elements is part of that block. Remove all z-index, remove using top and bottom, use only one. add height 1px to show shadow, and backgound: rgba(0,0,0,0,) to hide the block itself. You can't hide block and show shadow.

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	flex-wrap: wrap;
:+1:

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	width: 30%;
use flex-grow or smth like that

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +.article__title {
it is rather a header then title.

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	width: 85px;
never fixed width

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	background-image: url(img/pre-footer.png);
wtf, isn't it just black?)

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	color: #fff;
:+1:

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	display: flex;
stop. inside this tag is the only child center, why flex?

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	border-bottom: 3px solid black;
it's not just a line. Use picture with :after

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	width: 70px;
nope

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	list-style-image: url(img/Arrow.png)
:+1:

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +.pre-footer__name,
better create class pre-footer__input and use it

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	/*не знаю как сделать эффект вжатости*/
try box inner shadow

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	/*не знаю как сделать эффект вжатости*/
or border-style inset

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +	resize: none;
:+1:

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +.placeholder::-webkit-input-placeholder {
why? placeholder is disappearing automatically when focus.Why you need this?

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +/**********animation******************/
you can move it out to separate file I guess

2017-03-17 12:12 UTC, egemon commented on lesson4/style.css
> +@media (max-width: 1120px) {
and this one too

2017-03-17 15:21 UTC, VladyslavAbramov commented on lesson4/index.html
> +		<div class="header__centre">
в каждом name__centre я исполюзую разные значения display, position и т.д. поэтому я не стал только ради width:80% and margin: 0 auto создавать отдельный класс

2017-03-17 15:24 UTC, VladyslavAbramov commented on lesson4/index.html
> +				<img class="header__picture" src="img/logo.png">
я не понял, что ты имеешь в виду

2017-03-17 15:24 UTC, VladyslavAbramov commented on lesson4/index.html
> +			<div class="article__item">
здесь я тоже не понял, что нужно исправить

2017-03-17 15:26 UTC, VladyslavAbramov commented on lesson4/style.css
> +	background-image: url(img/grad.png);
не могу понять какой градиент здесь использовать: линейный или радиальный?

2017-03-17 15:27 UTC, VladyslavAbramov commented on lesson4/style.css
> +	align-items: center;
С помощью align-items: center я выравниваю блок с текстом по центру

2017-03-17 15:28 UTC, VladyslavAbramov commented on lesson4/style.css
> +	z-index: 2; /* не знаю почему, но не работает */
я хочу, чтобы элемент который создает тень был под .subscription, а сама тень выглядывала из-за него

2017-03-17 15:29 UTC, VladyslavAbramov commented on lesson4/style.css
> +	width: 30%;
а почему нельзя просто обойтись width`ом?

2017-03-17 15:30 UTC, VladyslavAbramov commented on lesson4/style.css
> +	background-image: url(img/pre-footer.png);
фон не просто черный, а с мелкими белыми точками

2017-03-17 15:31 UTC, VladyslavAbramov commented on lesson4/style.css
> +.pre-footer__name,
я не хотел присваивать тегу textarea класс pre-footer__input

2017-03-17 15:32 UTC, VladyslavAbramov commented on lesson4/style.css
> +.placeholder::-webkit-input-placeholder {
обычно placeholder исчезает при вводе текста. а так он исчезает при фокусе

2017-03-21 13:34 UTC, egemon commented on lesson4/index.html
> +		<div class="header__centre">
это можно, есть принцип DRY=don't repeat yourself. Это как бы общий принцип, что если нужно одно и то же писать несколько раз - лучше это вынести в одно место. Потому что если будут изменения - их нужно будет сделть только в одном месте. Например клиент захочит увеличить ширину странички.

2017-03-21 13:34 UTC, egemon commented on lesson4/index.html
> +				<img class="header__picture" src="img/logo.png">
в смысле что картинку нужно обернуть в ссылку, знаешь как в ВК когда нажимаешь на эмблемы - переходишь на главную страницу.

2017-03-21 13:37 UTC, egemon commented on lesson4/index.html
> +			<div class="article__item">
в смысле что каждый из 6ти одинаковы блочков - как бы целый организм. Поэтому лучше главный контейнер этого организма будет блоком (то есть article,  а не article__item) а внутри него все останется так же. Понял?

2017-03-21 13:38 UTC, egemon commented on lesson4/style.css
> +	background-image: url(img/grad.png);
похоже на радиальный со смещением. Используй проценты или backgorund-postition

2017-03-21 13:39 UTC, egemon commented on lesson4/style.css
> +	align-items: center;
сори не заметил

2017-03-21 13:41 UTC, egemon commented on lesson4/style.css
> +	width: 30%;
Можно, просто флекс дает большую гибкость единиц в этом плане. Смысл в том, что ты как бы используешь мощный инструмент, но только в полсилы.

2017-03-21 13:41 UTC, egemon commented on lesson4/style.css
> +	background-image: url(img/pre-footer.png);
согласен;)

2017-03-21 13:42 UTC, egemon commented on lesson4/style.css
> +	background-image: url(img/pre-footer.png);
там кстати лучше всего сделать крутой хак - вырезать кусочек этого фона, а потом размножить его с помощью background-repeat. Так ты уменьшишь время загрузки страницы

2017-03-21 13:42 UTC, egemon commented on lesson4/style.css
> +.pre-footer__name,
понял тебя, тогда вместо инпут исползуй филд. Они по смыслу близки верно? Есть смысл вынести общее.

2017-03-21 13:43 UTC, egemon commented on lesson4/style.css
> +.placeholder::-webkit-input-placeholder {
Согласен

2017-03-24 13:40 UTC, egemon approved these changes
UI:
1) to make shadows on form use pseudo elements with images not with shadows. 
2) all 'see more' buttons should be alligned no matter how long is text above - fix this
3) you don't need file footer.png since you have footer1.png
4) do with header the same way
5) page1miror is useless
6) shadow png is kind of what you need but seems like you forget to use it

2017-03-24 13:40 UTC, egemon commented on lesson4/index.html
> +	<link rel="stylesheet" type="text/css" href="media_queries.css">
:+1:

2017-03-24 13:40 UTC, egemon commented on lesson4/index.html
> +			<div class="container">
I would use here smth like class article or news

2017-03-24 13:40 UTC, egemon commented on lesson4/index.html
> +				<img class="container__picture--big" src="img/container4.png">
container__picture container__picture--big - it is important to use both, but I didn't find any styles for bid. Do you need it?

2017-03-24 13:40 UTC, egemon commented on lesson4/index.html
> +				<div class="footer__text">
seems like paragraphs <p>

2017-03-24 13:40 UTC, egemon commented on lesson4/index.html
> +				<div class="footer__title">
seems like h3

2017-03-24 13:40 UTC, egemon commented on lesson4/index.html
> +						Some Menu Link 1
link is important word here. should have link inside

2017-03-24 13:40 UTC, egemon commented on lesson4/media_queries.css
> +		flex-direction: column;
:+1:

2017-03-24 13:40 UTC, egemon commented on lesson4/style.css
> +.centre {
:+1:

2017-03-24 13:40 UTC, egemon commented on lesson4/style.css
> +	z-index: 200;
always use reasonable values. 1 is enough here

2017-03-24 13:40 UTC, egemon commented on lesson4/style.css
> +.subscription:before, .subscription:after {
these thing seems not correct like on psd. Please use picture.

2017-03-24 13:40 UTC, egemon commented on lesson4/style.css
> +	flex-wrap: wrap;
:+1:

2017-03-24 13:40 UTC, egemon commented on lesson4/style.css
> +.footer__title:after {
:+1:

2017-03-24 13:40 UTC, egemon commented on lesson4/style.css
> +    background-image: url(img/underline.png);
cool guys would use repeat even here. I'm not the one)))

2017-03-24 19:32 UTC, merged